### ISSUE TITLE
finetuning error

### ISSUE THREAD

**Issue by zakidotai** [BangLab-UdeM-Mila/NLP4MatSci-HoneyBee#1]
Hi, Thanks for sharing the wonderful work.
I am encountering the following error while running the finetuning. It seems something in dataset is broken.

Can you please guide me if I am  missing anything?
`Traceback (most recent call last):
  File "/scratch/civil/phd/cez198233/lms_trained/NLP4MatSci-HoneyBee/uniform_finetune.py", line 418, in <module>
    train(args)
  File "/scratch/civil/phd/cez198233/lms_trained/NLP4MatSci-HoneyBee/uniform_finetune.py", line 222, in train
    data, model, tokenizer = get_data_model(args)
  File "/scratch/civil/phd/cez198233/lms_trained/NLP4MatSci-HoneyBee/uniform_finetune.py", line 135, in get_data_model
    merge_data = concatenate_datasets([load_dataset("json", data_files=fname)["train"] for fname in args.data])
  File "/scratch/civil/phd/cez198233/lms_trained/NLP4MatSci-HoneyBee/uniform_finetune.py", line 135, in <listcomp>
    merge_data = concatenate_datasets([load_dataset("json", data_files=fname)["train"] for fname in args.data])
  File "/home/civil/phd/cez198233/anaconda3/envs/llama/lib/python3.9/site-packages/datasets/load.py", line 2136, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/civil/phd/cez198233/anaconda3/envs/llama/lib/python3.9/site-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/home/civil/phd/cez198233/anaconda3/envs/llama/lib/python3.9/site-packages/datasets/builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/civil/phd/cez198233/anaconda3/envs/llama/lib/python3.9/site-packages/datasets/builder.py", line 1813, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/home/civil/phd/cez198233/anaconda3/envs/llama/lib/python3.9/site-packages/datasets/builder.py", line 1958, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset`

**Comment by yusonghust** [comment]
It seems to be a problem with the system environment configuration.  "bitsandbytes", "peft" and CUDA versions are very important.

**Comment by zakidotai** [comment]
> It seems to be a problem with the system environment configuration. "bitsandbytes", "peft" and CUDA versions are very important.

We have been able to fix this.  Thanks for the reply. I have another issue, opening it as a new issue and closing this one.

**Comment by yusonghust** [comment]
您的来信已收到，谢谢！祝身体健康，万事如意！宋宇华中科技大学韵苑23#

**Comment by zakidotai** [comment]
> 您的来信已收到，谢谢！祝身体健康，万事如意！宋宇华中科技大学韵苑23#

非常感谢
